spring:
  application:
    name: Spring Security Jwt 3

  datasource:
    url: jdbc:postgresql://localhost:5432/secjwt3
    username: postgres
    password: ${DB_PASSWORD} # Reads from .env
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8443  # HTTPS port


app:
  jwt:
    secret: ${JWT_SECRET} # Reads from .env
  security:
    pepper: ${PEPPER_KEY} # Reads from .env
    max-failed-attempts: 5
    lockout-duration-minutes: 1

